.application.name=task-management-api

# Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate validates the schema but does not modify it
spring.jpa.hibernate.ddl-auto=validate

# Database schema changes are managed by Flyway
spring.flyway.enabled=true

# Prevent database access from leaking into the web layer
spring.jpa.open-in-view=false